### ISSUE TITLE
Сортировка редиректов

### ISSUE THREAD

**Issue by Doctor-Zi** [ideals/Ideal-CMS#131]
При добавлении редиректа присваивать ему последний номер в списке.

При удалении редиректа, изменять номера редиректов ниже по списку.

Нужно сделать возможность перетаскивать мышкой редиректы вверх-вниз (см. в админке раздел "Сервис" и подпункт "Редиректы"). В jQueryUI есть такой плагинчик, который сейчас уже подключён (в ветке feature/addon). При сортировке должен меняться номер редиректа, отображаемый в левой колонке.

Также необходимо добавить сортировку списка по столбцам (по клику на название столбца), но при сохранении списка, он должен быть отсортирован по порядковому номеру редиректа.

Кроме того, если список отсортирован не по порядковому номеру, не должна быть доступна сортировка элементов перетаскиванием, она должна работать только при сортировке по номеру редиректа.

Внизу списка сделать кнопку "Упорядочить по полю «Откуда»", по этой кнопке редиректы упорядочиваются по полю «Откуда» при этом меняются и их номера.

Все основные действия производятся в файлике Ideal\Structure\Service\Redirect\Action.php а первоначальный список редиректов формируется в файле Ideal\Structure\Service\Redirect\RewriteRule.php строки 290-299

**Comment by ideals** [comment]
Перенёс в #3
