### ISSUE TITLE
Модернизация резервных копий

### ISSUE THREAD

**Issue by Doctor-Zi** [ideals/Ideal-CMS#153]
Предлагаю несколько вещей для раздела Сервис-Резервные копии
1. Возможность оставлять комментарии, что бы потом можно было понять для чего был сделал тот или иной бекап
2. Добавить листалку
3. Сохранять данные о версии админки
4. Дополнительная возможность архивировать папку с окончанием .c
5. Дополнительно указывать оптимальное кол-во бекапов(предлагаю 10), а когда делается 11, система предлагает удалить один из ранее созданных.

**Comment by ideals** [comment]
1. Заморочек много, а пользоваться никто этим не будет. Мне кажется, что тут хватит пока пункта за номером три
2. Не нужно. Бэкапов не должно быть много. Если их становится столько, что требуется листалка, то надо что-то удалять
3. Согласен. Это можно отдельным issue оформлять
4. Да. Я думаю о полной архивации всех данных на сайте. А почему только _c?
5. Тоже думаю не нужно. Пусть люди сами решают, сколько должно быть бэкапов

Вообще надо стремится к тому, чтобы было как меньше кода в админке, чем меньше кода, тем проще его поддерживать. Поэтому надо искать баланс между количеством кода и надёжностью работы сайта.

**Comment by Doctor-Zi** [comment]
1. Не вижу так уж много замарочек, просто файл в котором название файла и комент
2. Быть и не нужно, но их порой много что мешает так что это скорее более дань перфекционизму
4. Потому что данные о админке уже получены в пункте 3
5. Если решают что им нужна свалка то пусть , тогда нужен пункт 2

**Comment by ideals** [comment]
1. Если отдельными файлами оформлять и только если этот коммент добавили, то можно
2. Не делаем
3. Сохраняем версию админки в названии файла
4. Не вижу смысла в частичном бэкапе файлов. У нас данные и в папке админки лежат, и в корне сайта. Если уж бекапить файлы, то все.
5. Не делаем.

**Comment by ideals** [comment]
Резюме:

1. Возможность добавить комментарий к бэкапу (доп. кнопка рядом с кнопками импорта и удаления). При нажатии на которую добавляется или редактируется комментарий, а при наведении — отображается текст комментария в tooltip. Сам комментарий хранится отдельным файлом с таким же именем, как бэкап, но с расширением txt

2. В названии файла бэкапа добавлять номер версии админки (например, v2.1). Версия админки берётся из README файла в корне папки Ideal

**Comment by ideals** [comment]
Реализовано: aac0a1b96b87436234ab782c0719bc4b67508283
