### ISSUE TITLE
Защита от брутфорса доступа к админке

### ISSUE THREAD

**Issue by ideals** [ideals/Ideal-CMS#175]
В таблице пользователей добавляется поле — счётчик неудачных попыток авторизации.
Если пользователь авторизовался, то он сбрасывается в 0. Если пароль неверный, то с каждой неудачной попыткой авторизации, счётчик увеличивается на единицу. И в зависимости от этого счётчика, при каждой авторизации делается задержка ответа, которая увеличивается в [арифметической прогрессии](https://ru.wikipedia.org/wiki/%D0%90%D1%80%D0%B8%D1%84%D0%BC%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D1%8F) с шагом 5 секунд и начальным значением 0. То есть при первой неудачной попытке, задержка 0, при второй — 5 секунд, при третьей — 10 секунд и так далее, вплоть до 60 секунд. Далее задержка остаётся 60 секунд и не меняется.

**Comment by ideals** [comment]
В setup\update добавить папку с номером предстоящей версии и там сделать скрипт, добавляющий поле счётчика неудачных попыток к существующей таблице пользователей (учесть что префиксы у таблиц зависят от настроек)

**Comment by MORWAL** [comment]
Принял в работу.

**Comment by MORWAL** [comment]
Предложил реализацию в пуллреквесте https://github.com/ideals/Ideal-CMS/pull/264

**Comment by ideals** [comment]
Реализовано
