### ISSUE TITLE
Ошибка при повторном нажатии кнопки "Применить"

### ISSUE THREAD

**Issue by Nexor0** [ideals/Ideal-CMS#249]
Если повторно нажать кнопку применить, при создании новой страницы, получаем сообщение об ошибке "URL: ... уже используется!".

**Comment by ideals** [comment]
Это последствия внедрения проверки дублированных урлов eb8b462 . Нужно сделать таким образом, чтобы после первого нажатия кнопки "Применить", дальнейшие нажатия на неё обрабатывались как редактирование, а не как создание.

**Comment by MORWAL** [comment]
Проблема была на фронтенде. А именно в том, что после удачного срабатывания кнопки "Применить" первый раз, не прописывался идентификатор только что созданного элемента структуры в глобальную переменную. Как следствие при повторном нажатии кнопки "Применить"   использовались не верные данные для сравнения адресов в проверке дублирования урлов.

**Comment by ideals** [comment]
Сделано
