### ISSUE TITLE
Получение источника перехода пользователя совершившего заказ на сайте

### ISSUE THREAD

**Issue by MORWAL** [ideals/Ideal-CMS#263]
Если пользователь совершает заказ, то необходимо получать информацию о том, откуда он пришёл изначально (Яндекс, Google, другие сайты). 

Продумать вариант сохранения рефереров во "флеш куках" вместо/вместе со стандартными куками. 

Во фреймворке форм добавить поле для отправки, помимо всего прочего, дополнительных данных из куков.

Продумать и реализовать защиту от спама.

Сохранять все заказы в справочник "Заказы с сайта".

Сделать раздел «Конверсия» в пункте «Сервис», этот раздел будет идти в стандартной поставке Ideal CMS. В этом разделе отображаются графики кол-ва заказов в неделю для каждого вида источников перехода. Источники будут следующие : Прямые заходы, Яндекс, Google, Директ, Adwords, Другие сайты

**Comment by MORWAL** [comment]
Принял в работу.

**Comment by ideals** [comment]
Продумать как будет сохраняться referrer если включено файловое кэширование. Возможный вариант — сохранение referer с помощью javascript в cookies
Через document.referrer

**Comment by ideals** [comment]
Сделано.
