### ISSUE TITLE
Улучшение обработки 404-ых ошибок

### ISSUE THREAD

**Issue by ideals** [ideals/Ideal-CMS#276]
Выделить известные 404-ые ошибки в отдельный файл known404.php
Создать справочник 404-ых ошибок
Сделать новый пункт в разделе сервис "404 ошибки". Там две вкладки "Известные 404" и "Правила игнорирования 404". В первой вкладке — те адреса по которым не происходит обращение в БД и сразу выдаётся 404, а во второй — набор правил по которым определённые страницы не попадают в список 404 в БД и в список известных 404 в файле.
__Принцип действия__
Если произошла 404-ошибка и урла нет в правилах игнорирования 404-ых, записываем в БД, если урл  уже есть в БД, увеличиваем кол-во на 1. Если количество превышает 10, то записываем в файл с известными 404-ошибками. 
Роутер смотрит, не подходит ли запрошенная страница под url в файле с известными 404, если да, то выдает 404-ую без запросов к БД. 
Если произошла 404 ошибка и юзер залогинен в админку, то в сообщении написать об этом, а в БД не записывать и счётчик у уже записанных в БД не увеличивать

**Comment by MORWAL** [comment]
Принял в работу

**Comment by MORWAL** [comment]
принял в работу
