### ISSUE TITLE
Проверка целостности скриптов CMS

### ISSUE THREAD

**Issue by ideals** [ideals/Ideal-CMS#280]
По нажатию на кнопку проверки в разделе Сервис/Проверка целостности/Файлы CMS запускается проверка на добавление/удаление/модификацию файлов в папке Ideal с уведомлением о модифицированных файлах.
А также сделать скрипт, генерирующий массив всех файлов с их хэшами для проверки целостности файлов. Файл должен быть в папке setup/prepare/hash_files.php Его запуск производится однократно, перед релизом CMS. Результирующий файл с массивом кладётся в ту же папку.

**Comment by MORWAL** [comment]
Принял в работу.

**Comment by ideals** [comment]
Сделано
