### ISSUE TITLE
Локальное обновление

### ISSUE THREAD

**Issue by ideals** [ideals/Ideal-CMS#281]
Сделать скрипт локального обновления на одну версию для тестовых целей.
Для тестовых целей нужно проверить запуск всех скриптов обновления локально, без подключения к серверу обновлений.
Для этого делаем файлик setup/update.php, который может запускаться только из консоли (при запуске через веб-сервер выдаёт ошибку) и выполняет запуск неустановленных скриптов обновления.

**Comment by MORWAL** [comment]
Принял в работу

**Comment by ideals** [comment]
Сделано.
