### ISSUE TITLE
Перенести функционал модуля Yandex в ядро.

### ISSUE THREAD

**Issue by MORWAL** [ideals/Ideal-CMS#293]
Сейчас модуль Yandex предоставляет возможность использовать поиск от Яндекса. Нужно перенести этот функционал в ядро. Добавить вкладку "Яндекс" в раздел "Сервис/Настройки".
На этой вкладке нужно сделать поля "Логин" и "Ключ" для подключения к "xml.yandex.ru".

**Comment by MORWAL** [comment]
Принял в работу.

**Comment by ideals** [comment]
Сделано.
