### ISSUE TITLE
Сжатие ресурсов

### ISSUE THREAD

**Issue by romazan** [ideals/Ideal-CMS#31]
Предлагаю добавить в функционал очень важную фичу сжатия ресурсов, так как на некоторых хостингах (в частности на мастерхосте) не работает gzip-сжатие.

PS: http://www.softtime.ru/forum/read.php?id_forum=1&id_theme=82001

**Comment by ideals** [comment]
Так, как сделано по указанной ссылке мы делать не будем. Уж слишком много ресурсов будет тратиться на создание zip-файла.

Нужно сделать следующим образом. В файлы min.gen.php добавить закомментированный код для генерации gzip-файла при объединении css и файлик no-gzip.htaccess с правилами переадресации на gzip-файл. 

Соответственно там где нужно будет подключить ручное сжатие в gzip, нужно будет раскомментировать код и файл no-gzip.htaccess переименовать в .htaccess

Как правильно сделать .htaccess и как должна формироваться сжатая и несжатая версии css и js-файлов нужно прочитать тут: http://webo.in/articles/habrahabr/07-gzip-all/
__Внимание, читать надо всю статью целиком!__

**Comment by ideals** [comment]
Подумал-подумал.. Слишком замысловатая схема. 
Кроме того, на мастерхосте сжатие ресурсов работает. 
Посмотри на тот же сайт www.raspilen.ru
Так что эту задачу закрываем.
