### ISSUE TITLE
Создание аддона Фотогалерея (Photo)

### ISSUE THREAD

**Issue by ideals** [ideals/Ideal-CMS#317]
Требуется сделать аддон, в котором с помощью CKFinder можно выбрать несколько файлов изображений (одновременно), они отобразятся списком с превьюшками и их можно будет передвигать мышкой (jquery ui плагин sortable) и делать подписи для каждой картинки

**Comment by MORWAL** [comment]
Принял в работу.

**Comment by ideals** [comment]
У нас выбор файла через CKFinder реализован в поле Image. Но там выбирается только один файл. Чтобы можно было выбрать несколько файлов, надо делать другую js-функцию, получающую данные от CKFinder. См доки http://docs.cksource.com/ckfinder_2.x_api/symbols/CKFinder.config.html#.selectActionFunction , а также может быть потребуется selectActionData (она там чуть выше в документации)

**Comment by ideals** [comment]
Сделано
