### ISSUE TITLE
Проблемы при удалении аддонов и элементов с аддонами

### ISSUE THREAD

**Issue by ideals** [ideals/Ideal-CMS#320]
1.
При удалении элемента должны удаляться все привязанные к нему аддоны

2.
Заходим в редактирование элемента
Переходим на вкладку аддона
Удаляем этот аддон
Заголовок вкладки исчезает, а контент вкладки остаётся.

Нужно чтобы исчезал и контент и фокус переключался на левую доступную вкладку

А также запись в таблице аддонов должна удаляться при сохранении элемента.

**Comment by MORWAL** [comment]
Принял в работу.
