### ISSUE TITLE
Ошибка при создании backup

### ISSUE THREAD

**Issue by Doctor-Zi** [ideals/Ideal-CMS#331]
Ошибка [8] Undefined index: Ideal-CMS, в строке 40 файла Ideal/Structure/Service/Backup/ajaxCreateDumpAction.php

**Comment by ideals** [comment]
Метод, который не возвращал нужное значение был исправлен 8-го июня. Возможно ты ещё на старой версии получал эту ошибку. Сейчас я её нигде обнаружить не смог.
