### ISSUE TITLE
Ошибка при загрузки файла backup на сервер

### ISSUE THREAD

**Issue by Doctor-Zi** [ideals/Ideal-CMS#332]
Пишет что "Ошибка при загрузке файла", файл не появляется. Обновляем страницу, файл есть.

**Comment by ideals** [comment]
Это сообщение возникает, когда jquery думает, что не удалось выполнить ajax-запрос. Так что чтобы понять, в чём тут ошибка, надо смотреть ответ сервера. Сейчас эту ошибку не смог повторить ни локально, ни глобально.

**Comment by Doctor-Zi** [comment]
adminka/Mods/NameMod/README.md): failed to open stream: No such file or directory, в строке 140 файла adminka/Ideal/Structure/Service/UpdateCms /Versions.php
Ошибка [2] Invalid argument supplied for foreach(), в строке 115 файла adminka/Ideal/Structure/Service/UpdateCms/Versions.php
Ошибка [8] Undefined index: Ideal-CMS , в строке 25 файла adminka/Ideal/Structure/Service/Backup/ajaxUploadFileAction .php

Вот такая ошибка вылезает при заливки файла backup. Ошибка возникает из-за отсутствия файла readme.md в папке с модулем

**Comment by ideals** [comment]
Проблему понял. Починим.
