### ISSUE TITLE
Починить поле выбора шаблонов

### ISSUE THREAD

**Issue by ideals** [ideals/Ideal-CMS#350]
С данным плагином совершенно невозможно работать с указанием кастомных файлов шаблона (не выбирая из списка). Во-первых, когда вводишь имя файла, нужно обязательно выбирать Add в выпадающем списке, иначе введённый текст не добавится, во-вторых, отредактировать текст нельзя, только полностью стереть и заново вводить со всеми теми же неудобствами. 
Возможно что нужно будет заменить на другой плагин

**Comment by MORWAL** [comment]
Принял в работу.

**Comment by ideals** [comment]
Готово
