### ISSUE TITLE
Проблемы при файловом кэшировании

### ISSUE THREAD

**Issue by ideals** [ideals/Ideal-CMS#363]
1. Не нужно кешировать 404-ые страницы. То есть если запрошен несуществующий url, то соответствующих файлов на диске создавать не надо

2. При запросе урла с get-параметрами эти самые параметры должны отбрасываться и страница должна создаваться без них. А то сейчас при запросе с get-параметрами создалась папка, в виде query_string, а в ней лежит файл index.html (запрос шёл к главной странице)

**Comment by MORWAL** [comment]
принял в работу
