### ISSUE TITLE
Поддержка Postgres

### ISSUE THREAD

**Issue by des1roer** [ideals/Ideal-CMS#399]
Планируется ли поддержка Postgres?

**Comment by ideals** [comment]
Пока нет, так как не вижу в этом особого смысла, всё и в MySQL нормально работает. Если есть какая-то очень большая потребность именно в Postgress, то нужно всего лишь подправить класс работы с БД: Core\Db.php
Расширение mysqli было выбрано из-за того, что в нём поддерживаются множественные запросы и работает оно чуть более оперативно, чем PDO.

**Comment by des1roer** [comment]
так postgres держит гораздо более серьезные нагрузки нежели мускул

**Comment by ideals** [comment]
Очень сильно сомневаюсь, что Postgres сможет работать быстрее и лучше, чем MySQL в режиме MyISAM. У нас были нагрузки свыше 5000 посетителей у день и на обычном виртуальном хостинге всё работало без сбоев. С большей посещаемостью не приходилось сталкиваться.
