### ISSUE TITLE
Перенос страниц из раздела в раздел.

### ISSUE THREAD

**Issue by romazan** [ideals/Ideal-CMS#4]
Сейчас приходится создавать новую в нужном разделе. А нужно сделать на страничке редактирования, к примеру, выпадающий список, в котором будет выбираться соответствующая рубрика. И дополнительно там же можно будет создать новую рубрику и выбрать для нее родительскую (если требуется).

Также нужно продумать массовый перенос нескольких страниц из одного раздела в другой.

**Comment by romazan** [comment]
Можно в автоматическом режиме создавать редирект. Если эта страничка потом будет переноситься опять куда-то, то, соответственно будет создаваться второй редирект, чтобы не было двойного редиректа, можно оповещать об этом. Но для этого нужен будет dashboard, в котором будет иконка, на которой будут информер, оповещающий, что у нас в редиректах есть двойные.

**Comment by ideals** [comment]
Перенёс в #3
