### ISSUE TITLE
Возможность отката при обновление

### ISSUE THREAD

**Issue by Doctor-Zi** [ideals/Ideal-CMS#434]
Привет!

Заметил что в скрипте обновления идет просто чтения файла *.sql и просто выполнение. Разве не лучше все это запихать в транзакцию и если все пошло по кривой то rollback сотворить?
Или вера что везде будет только MyISAM, а пользователь всегда будет делать backup перед обновлением?

Файл про который говорю /Ideal/Structure/Service/UpdateCms/Model.php

**Comment by ideals** [comment]
А разве скрипт не упадёт, если там только MyISAM? Я думал что так, поэтому InnoDb всерьёз не рассматривал. У нас до сих пор на некоторых хостингах его нет. То есть, если добавлять транзакции, то это уже ставить ограничение, что только БД с InnoDb подходит.

**Comment by Doctor-Zi** [comment]
Но ведь до проблемного участка запросы "до" будут отправлены к базе.

**Comment by ideals** [comment]
Будут. Но если цена за это переход только на InnoDb, то это надо серьёзно проверять, какие хостинги поддерживают, а какие нет. Я бы с удовольствием перешёл на PHP 7, но пока хостинги его не поддерживают — придётся куковать на 5.6 :)

**Comment by ideals** [comment]
Хотя сейчас посмотрел, на всех наших хостингах InnoDb есть :)
И если его поддержка есть, то START TRANSACTION и COMMIT прокатывают даже на MyISAM таблицах.
Тогда вопрос остаётся только в том, стоит ли замедление производительности в пять раз возможности выполнить откат при обновлении...
Надо провести тестирование, посмотреть, насколько действительно уменьшается скорость работы в реальных случаях использования.

**Comment by Doctor-Zi** [comment]
А кто говорит на полном применении. Этого вполне достаточно при обновлении.

**Comment by ideals** [comment]
Что значит "полное применение"? Речь идёт о том, что если ты делаешь таблицу InnoDb, то она работает медленнее, чем MyISAM на ВСЕХ видах запросов к ней.
