### ISSUE TITLE
Ведение списка заказчиков на сайте (MicroCRM)

### ISSUE THREAD

**Issue by ideals** [ideals/Ideal-CMS#457]
Задача
---

Необходимо отслеживать повторные обращения от одного и того же лида (учитывать реальные заявки с сайта, игнорируя тестовые и учитывать, что один чел может заказать с разных устройств, с разных почтовых ящиков и телефонов).

Решение
---

Для этого добавить таблицу i_ideal_structure_crm. В этой таблице будут храниться люди (в смысле их реквизиты), а каждый заказ должен быть привязан к опредёленной персоне.

При добавлении нового заказа система ищет, нет ли уже человека с таким Client ID, email или телефоном. Если такой человек есть, заказ привязывается к нему.

Client ID берётся из Google Analytics.

Если человека нет, то создаётся новый человек с указанными в заказе данными.

У менеджера должна быть возможность объединить несколько созданных людей. При объединении сливается список Client ID, телефонов, почт и заказов.

В списке людей создаётся тестовый человек, у которого телефон 00000000000 к нему будут относится все тестовые заказы.

Далее нужно исправить систему отображения конверсии: после вкладки "Общее кол-во" ([см. скриншот](https://docs.google.com/document/d/12J9Kfoq8-Z7Ka63KJaICR1pVi_SzTLpSi7Ro8bblhLQ/edit)) добавить вкладку "Кол-во лидов" и там отображать аналогичные данные, но из одного лида брать только одну — первую заявку.

А также нужно добавить чекбокс к фильтру — только новые лиды при нажатии на которую не учитываются заявки, отнесённые к тем лидам, по которым были заявки в предыдущих месяцах.

**Comment by MORWAL** [comment]
Взял в работу

**Comment by ideals** [comment]
Сделано
