### ISSUE TITLE
Утерян пароль от админпанели сайта

### ISSUE THREAD

**Issue by Vitaliy87** [ideals/Ideal-CMS#469]
Потерялся пароль единственный пароль от административной панели сайта. Подскажите как восстановить или сбросить его. Версия скрипта v2,3 если не ошибаюсь

**Comment by Vitaliy87** [comment]
Спасибо помогло

**Comment by ideals** [comment]
Пожалуйста. Обращайтесь, если что :)

**Comment by Vitaliy87** [comment]
Ну чтож обращаюсь) Подскажите пожайлуйста, пытаюсь создать карту сайта с помощью встроенного сервиса через админпанель. В результате скрипт завершается ошибкой и приходит такое уведомление на почту.
![2017-09-11 13 15 52](https://user-images.githubusercontent.com/31735607/30269956-85c2079c-96f3-11e7-921d-16b82d250351.png)
http://www.technostroy.ru/cvet-i-dizajn.html данная страница раньше была, но сейчас она удалена и именно на ней затыкается скрипт.

**Comment by ideals** [comment]
В уведомлении сообщается о том, что на странице Здравоохранение есть ссылка на несуществующую страницу. Нужно удалить эту ссылку со страницы Здравоохранение и пересобрать карту сайта.
