### ISSUE TITLE
Страница установки

### ISSUE THREAD

**Issue by Doctor-Zi** [ideals/Ideal-CMS#483]
Есть проблема когда устанавливаешь CMS в поле "Доменное имя сайта" можно ввести все что угодно, домен 3,4 и тд уровня, а редирект предлагает с www.*
Так же там же можно указать еще всякую дичь из серии http://www.* и редирект опять предлагает варианты не очень хорошие

**Comment by ideals** [comment]
Сделал уведомления о неправильном домене
