### ISSUE TITLE
timepicker

### ISSUE THREAD

**Issue by Doctor-Zi** [ideals/Ideal-CMS#486]
Ошибка в отображении, происходит наложение слоев

![error](https://user-images.githubusercontent.com/4368998/37255462-c45ed18a-255d-11e8-8395-38cc7ff0e78d.PNG)

**Comment by ideals** [comment]
Там скроллер появляется и кроме того, можно и с клавиатуры ввести. Увеличивать размер окна, как мне кажется, в данном случае нерационально.
